"""
Macro Regime Backtest
======================
Tests whether macro regime filtering improves C12 strategy performance.

  1. Baseline (no macro filter)
  2. Macro regime gating — skip LIQUIDITY_CRISIS days
  3. Regime-aware lot sizing — adjust lots by regime
  4. Per-regime breakdown — how does C12 perform in each macro environment?

Requires:
  - data/macro_history.csv (generated by macro.data_provider.download_history)

Usage:
    python backtest_macro_regime.py
"""
import time
from pathlib import Path

import numpy as np
import pandas as pd

from backtest import DataBundle, run_variant, calc_stats, print_comparison, aggregate_daily_pnl
from backtest.runner import (
    C12_KWARGS, load_m15, load_h1_aligned, add_atr_percentile, H1_CSV_PATH,
)
from backtest.engine import BacktestEngine
from strategies.signals import prepare_indicators
from macro import MacroDataProvider
from macro.regime_detector import MacroRegimeDetector, add_regime_column

SPREAD = 0.50
MACRO_CSV = Path("data/macro_history.csv")


def load_macro():
    if not MACRO_CSV.exists():
        print("  macro_history.csv not found, downloading...")
        provider = MacroDataProvider()
        provider.download_history(save_path=str(MACRO_CSV))

    df = pd.read_csv(str(MACRO_CSV), index_col='date', parse_dates=True)
    df = df.ffill()
    df = add_regime_column(df)
    print(f"  Macro: {len(df)} days, {df.index[0].date()} -> {df.index[-1].date()}")
    regime_counts = df['macro_regime'].value_counts()
    for regime, count in regime_counts.items():
        pct = count / len(df) * 100
        print(f"    {regime}: {count} days ({pct:.1f}%)")
    return df


def main():
    print("=" * 90)
    print("  MACRO REGIME BACKTEST")
    print("=" * 90)

    t0 = time.time()

    m15_raw = load_m15()
    h1_raw = load_h1_aligned(H1_CSV_PATH, m15_raw.index[0])
    m15_df = prepare_indicators(m15_raw.copy(), timeframe='M15')
    h1_df = prepare_indicators(h1_raw.copy(), timeframe='H1')
    h1_df = add_atr_percentile(h1_df)
    bundle = DataBundle(m15_df, h1_df)

    print("\n  Loading macro data...")
    macro_df = load_macro()

    # ── Part 1: With vs Without Macro Filter ──
    print("\n" + "=" * 90)
    print("  Part 1: Macro Regime Filter Effect")
    print("=" * 90)

    configs = [
        ("C12 (no macro)", {**C12_KWARGS, "spread_cost": SPREAD}),
        ("C12 + Macro Filter", {
            **C12_KWARGS, "spread_cost": SPREAD,
            "macro_df": macro_df, "macro_regime_enabled": True,
        }),
        ("C12+Adaptive (no macro)", {
            **C12_KWARGS, "spread_cost": SPREAD,
            "intraday_adaptive": True, "choppy_threshold": 0.35, "kc_only_threshold": 0.60,
        }),
        ("C12+Adaptive + Macro", {
            **C12_KWARGS, "spread_cost": SPREAD,
            "intraday_adaptive": True, "choppy_threshold": 0.35, "kc_only_threshold": 0.60,
            "macro_df": macro_df, "macro_regime_enabled": True,
        }),
    ]

    results = []
    for label, kw in configs:
        print(f"\n  Running {label}...", flush=True)
        stats = run_variant(bundle, label, verbose=False, **kw)
        results.append(stats)
        print(f"    N={stats['n_trades']}, Sharpe={stats['sharpe']:.2f}, "
              f"PnL=${stats['total_pnl']:.0f}, MaxDD=${stats['max_dd']:.0f}")

    print("\n" + "-" * 90)
    print("  Comparison")
    print("-" * 90)
    print_comparison(results)

    # ── Part 2: Per-Regime Breakdown ──
    print("\n" + "=" * 90)
    print("  Part 2: C12 Performance by Macro Regime")
    print("  (How does C12 perform in each macro environment?)")
    print("=" * 90)

    print("\n  Running full C12 backtest...", flush=True)
    base_kw = {**C12_KWARGS, "spread_cost": SPREAD}
    engine = BacktestEngine(m15_df, h1_df, label="C12-full", **base_kw)
    engine.run()
    all_trades = engine.trades

    print(f"  Total trades: {len(all_trades)}")

    detector = MacroRegimeDetector()
    regime_trades = {}

    for trade in all_trades:
        trade_date = pd.Timestamp(trade.entry_time).normalize()
        if trade_date.tz is not None:
            trade_date = trade_date.tz_localize(None)

        if trade_date in macro_df.index:
            row = macro_df.loc[trade_date]
            regime = row.get('macro_regime', 'unknown')
        else:
            regime = 'no_macro_data'

        if regime not in regime_trades:
            regime_trades[regime] = []
        regime_trades[regime].append(trade)

    print(f"\n  {'Regime':<30} {'N':>6} {'PnL':>10} {'WR%':>8} {'Avg$/tr':>10} {'MaxDD':>10}")
    print("  " + "-" * 78)

    for regime in sorted(regime_trades.keys()):
        trades = regime_trades[regime]
        n = len(trades)
        pnl = sum(t.pnl for t in trades)
        wins = sum(1 for t in trades if t.pnl > 0)
        wr = wins / n * 100 if n > 0 else 0
        avg = pnl / n if n > 0 else 0

        equity = []
        running = 0
        peak = 0
        max_dd = 0
        for t in sorted(trades, key=lambda x: x.entry_time):
            running += t.pnl
            equity.append(running)
            if running > peak:
                peak = running
            dd = peak - running
            if dd > max_dd:
                max_dd = dd

        print(f"  {regime:<30} {n:>6} ${pnl:>9.0f} {wr:>7.1f}% ${avg:>9.2f} ${max_dd:>9.0f}")

    # ── Part 3: Strategy Signal by Regime ──
    print("\n" + "=" * 90)
    print("  Part 3: Strategy Weight Suggestions by Regime")
    print("=" * 90)

    print(f"\n  {'Regime':<30} {'Lot Mult':>10} {'Buy':>6} {'Sell':>6} {'SL+':>6} {'Bias':>10}")
    print("  " + "-" * 72)

    from macro.regime_detector import MacroRegime
    for regime in MacroRegime:
        w = detector.get_strategy_weights(regime)
        print(f"  {regime.value:<30} {w['lot_multiplier']:>10.1f} "
              f"{'Y' if w['buy_enabled'] else 'N':>6} "
              f"{'Y' if w['sell_enabled'] else 'N':>6} "
              f"{'Y' if w['expand_sl'] else 'N':>6} "
              f"{w['regime_bias']:>10}")

    elapsed = time.time() - t0
    print(f"\n  Total time: {elapsed:.0f}s ({elapsed/60:.1f}min)")
    print("  Done!")


if __name__ == "__main__":
    main()
